### ISSUE TITLE
Will not make or manually compile

### ISSUE THREAD

**Issue by delahaya** [santoru/filewatcher#2]
When running `make` I receive this error...

```
cd lib && rm *.gch
rm: *.gch: No such file or directory
make: [fresh] Error 1 (ignored)
gcc -lbsm filewatcher.c lib/*.c -o bin/filewatcher
ld: can't open output file for writing: bin/filewatcher, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fresh] Error 1
```

When attempting to compile manually, I receive this message...

```
ld: can't open output file for writing: bin/filewatcher, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tmhoule** [comment]
it needs you to create the empty bin directory.  Then it can dump filewatcher into there.

**Comment by delahaya** [comment]
Got it.  Trying now.  Thanks for the quick reply!  Will report back with results.

**Comment by delahaya** [comment]
Nailed it!  We have success.  Thanks again!

**Comment by ghost** [comment]
Thanks @delahaya and @tmhoule for help! I didn't notice that I can't push empty directories.. my bad! With last commit should be solved.
