### ISSUE TITLE
Makefile bug

### ISSUE THREAD

**Issue by thomasareed** [santoru/filewatcher#4]
The makefile attempts to output to "bin/", which does not exist unless the user manually creates it. Thus the make fails with the distribution as-is.

**Comment by ghost** [comment]
Hi! Did you try using the updated version? This bug should be fixed with the commit 3d92e8c4afcf61fe1690dc2f3f95a68d4e64c91f that specify the Makefile to make also the bin directory.

**Comment by thomasareed** [comment]
Nope, the build I tried was a previous one. That looks like it'll fix the problem. Thanks!
